export const selectors = {
  buttonAddStopwatch: '.add',
  buttonClearInterval: '.interval__button-clear',
  buttonPause: '.stopwatch__button-pause',
  buttonStart: '.stopwatch__button-start',
  buttonInterval: '.stopwatch__button-interval',
  buttonReset: '.stopwatch__button-reset',
  buttonCloseIcon: '.stopwatch__close-icon',
  buttonInactiveClass: 'button_inactive',
  centiseconds: '#centiseconds',
  hours: '#hours',
  intervals: '.container-interval',
  intervalTemplate: '.interval',
  intervalTemplateId: 'interval-template',
  minutes: '#minutes',
  stopwatchContainer: '.center',
  stopwatchTemplate: '.container',
  stopwatchTemplateId: 'stopwatch-template',
  seconds: '#seconds',
  textInterval: '.interval__text',
},
intervalTemplate = document.getElementById(selectors.intervalTemplateId).content.querySelector(selectors.intervalTemplate),
stopwatchTemplate = document.getElementById(selectors.stopwatchTemplateId).content.querySelector(selectors.stopwatchTemplate),
stopwatchContainer = document.querySelector(selectors.stopwatchContainer),
buttonAddStopwatch = document.querySelector(selectors.buttonAddStopwatch);
